In [1]:
import pandas as pd
import numpy as np

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91949\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
fl=open(r'C:\Users\91949\Desktop\Niltech_files\spam.csv','r')
data=fl.read()
fl.close()

In [6]:
data

'ham\tGo until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...\nham\tOk lar... Joking wif u oni...\nspam\tFree entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C\'s apply 08452810075over18\'s\nham\tU dun say so early hor... U c already then say...\nham\tNah I don\'t think he goes to usf, he lives around here though\nspam\tFreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv\nham\tEven my brother is not like to speak with me. They treat me like aids patent.\nham\tAs per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune\nspam\tWINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341.

In [7]:
data=data.split('\n')

In [17]:
Class = []
for i in data:
    Class.append(i.split())

In [18]:
label=[]
features=[]
for i in data:
    try:
        i=i.split('\t')
        label.append(i[0])
        features.append(i[1])
    except:
        pass

In [19]:
label=label[:-1]

In [25]:
print(len(label),len(features))

5574 5574


In [27]:
pd_data=pd.read_csv(r'C:\Users\91949\Desktop\Niltech_files\spam.csv',header=None,sep='\t')

In [28]:
pd_data

0                                                  1
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [29]:
features=pd_data.drop(columns=0)
features

1
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568               Will ü b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [30]:
pd_data[0].replace(['ham','spam'],[1,0],inplace=True)

In [31]:
label=pd_data[0]

In [32]:
features=pd_data[1]
features

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: 1, Length: 5572, dtype: object

In [33]:
import re
values=[]
for i in features:
    z=re.sub("[^a-zA-A]",' ',i)
    values.append(z)

In [34]:
values

[' o until jurong point  crazy   Available only in bugis n great world la e buffet     ine there got amore wat   ',
 ' k lar     oking wif u oni   ',
 ' ree entry in   a wkly comp to win  A  up final tkts   st  ay        ext  A to       to receive entry question std txt rate     s apply            over   s',
 '  dun say so early hor      c already then say   ',
 ' ah   don t think he goes to usf  he lives around here though',
 ' ree sg  ey there darling it s been   week s now and no word back    d like some fun you up for it still   b ok   x  std chgs to send        to rcv',
 ' ven my brother is not like to speak with me   hey treat me like aids patent ',
 'As per your request   elle  elle   ru  innaminunginte  urungu  ettam   has been set as your callertune for all  allers   ress    to copy your friends  allertune',
 '         As a valued network customer you have been selected to receivea      prize reward   o claim call               laim code         alid    hours only ',
 ' ad you

In [35]:
pd_data['text']=values

In [36]:
pd_data

0                                                  1  \
0     1  Go until jurong point, crazy.. Available only ...   
1     1                      Ok lar... Joking wif u oni...   
2     0  Free entry in 2 a wkly comp to win FA Cup fina...   
3     1  U dun say so early hor... U c already then say...   
4     1  Nah I don't think he goes to usf, he lives aro...   
...  ..                                                ...   
5567  0  This is the 2nd time we have tried 2 contact u...   
5568  1               Will ü b going to esplanade fr home?   
5569  1  Pity, * was in mood for that. So...any other s...   
5570  1  The guy did some bitching but I acted like i'd...   
5571  1                         Rofl. Its true to its name   

                                                   text  
0      o until jurong point  crazy   Available only ...  
1                          k lar     oking wif u oni     
2      ree entry in   a wkly comp to win  A  up fina...  
3       dun say so early hor      c already then say     
4      ah   don t think he goes to usf  he lives aro...  
...                                                 ...  
5567   his is the  nd time we have tried   contact u...  
5568                ill   b going to esplanade fr home   
5569   ity    was in mood for that   o   any other s...  
5570   he guy did some bitching but   acted like i d...  
5571                          ofl   ts true to its name  

[5572 rows x 3 columns]

In [37]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91949\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [38]:
from nltk.tokenize import word_tokenize
pd_data['text']=pd_data['text'].apply(word_tokenize)

In [39]:
from nltk.stem import WordNetLemmatizer

In [40]:
lemmatizer=WordNetLemmatizer()

In [41]:
values=[]
for i in pd_data['text']:
    lemmatized_output = ' '.join([lemmatizer.lemmatize(w) for w in i])
    values.append(lemmatized_output)

In [42]:
pd_data['text']=values

In [43]:
pd_data

0                                                  1  \
0     1  Go until jurong point, crazy.. Available only ...   
1     1                      Ok lar... Joking wif u oni...   
2     0  Free entry in 2 a wkly comp to win FA Cup fina...   
3     1  U dun say so early hor... U c already then say...   
4     1  Nah I don't think he goes to usf, he lives aro...   
...  ..                                                ...   
5567  0  This is the 2nd time we have tried 2 contact u...   
5568  1               Will ü b going to esplanade fr home?   
5569  1  Pity, * was in mood for that. So...any other s...   
5570  1  The guy did some bitching but I acted like i'd...   
5571  1                         Rofl. Its true to its name   

                                                   text  
0     o until jurong point crazy Available only in b...  
1                                 k lar oking wif u oni  
2     ree entry in a wkly comp to win A up final tkt...  
3               dun say so early hor c already then say  
4     ah don t think he go to usf he life around her...  
...                                                 ...  
5567  his is the nd time we have tried contact u hav...  
5568                   ill b going to esplanade fr home  
5569     ity wa in mood for that o any other suggestion  
5570  he guy did some bitching but acted like i d be...  
5571                              ofl t true to it name  

[5572 rows x 3 columns]

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(analyzer='word')
vectorizer.fit(pd_data["text"])

CountVectorizer()

In [45]:
print(vectorizer.vocabulary_)

{'until': 6836, 'jurong': 3441, 'point': 4978, 'crazy': 1460, 'available': 630, 'only': 4535, 'in': 3172, 'bugis': 984, 'great': 2698, 'world': 7245, 'la': 3538, 'buffet': 983, 'ine': 3205, 'there': 6449, 'got': 2670, 'amore': 293, 'wat': 7067, 'lar': 3573, 'oking': 4450, 'wif': 7164, 'oni': 4530, 'ree': 5346, 'entry': 2081, 'wkly': 7213, 'comp': 1325, 'to': 6541, 'win': 7176, 'up': 6839, 'final': 2370, 'tkts': 6530, 'st': 6095, 'ay': 664, 'ext': 2260, 'receive': 5318, 'question': 5196, 'std': 6130, 'txt': 6695, 'rate': 5256, 'apply': 413, 'over': 4727, 'dun': 1830, 'say': 5655, 'so': 5970, 'early': 1871, 'hor': 2981, 'already': 256, 'then': 6443, 'ah': 155, 'don': 1761, 'think': 6461, 'he': 2829, 'go': 2646, 'usf': 6888, 'life': 3654, 'around': 490, 'here': 2874, 'though': 6477, 'sg': 5766, 'ey': 2266, 'darling': 1543, 'it': 3333, 'been': 763, 'week': 7103, 'now': 4312, 'and': 317, 'no': 4273, 'word': 7238, 'back': 681, 'like': 3665, 'some': 5983, 'fun': 2548, 'you': 7363, 'for': 2457

In [50]:
vector = vectorizer.fit_transform(pd_data['text'])

In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(vector,pd_data['text'],test_size=0.2)

In [58]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [59]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_predict=clf.predict(x_test)
print('accuracy',round(accuracy_score(y_test,y_predict)*100,4),'%')
print('confusion matrix\n',confusion_matrix(y_test,y_predict))

accuracy 12.5561 %
confusion matrix
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [60]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 10)
clf.fit(x_train,y_train)
predict2 = clf.predict(x_test)
print(accuracy_score(y_test,predict2))

0.12197309417040358
